schema_version = "1.0.0"

id = "miku_miku_physics"
version = "2.2.1"
name = "MikuMikuPhysics"
tagline = "External Bullet 2.82 runtime for mmd_tools PMX physics"
maintainer = "克里斯提亚娜"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

tags = ["Animation"]
